### ISSUE TITLE
多次验证失败 没有返回

### ISSUE THREAD

**Issue by baiRookie** [wuwuFQ/FQLockSDK#1]
FQBiometryContext.biometryAuth {
                AccountLockHelp().setLocalAllEnable(isEnable: true, userId: kDataManager.user.uid)
                AccountLockHelp().setBiometryAuthEnable(isEnable: true, userId: kDataManager.user.uid)
            } failureHandler: { (error) in
                self.faceIDSwitch?.isOn = false
                self.tableView.reloadData()
            }

**Comment by baiRookie** [comment]
此处在多次失败之后，点击取消之后没有返回错误

**Comment by baiRookie** [comment]
面容识别失败三次后会弹出系统密码验证，不输入密码点取消还有两次面容识别，如果都失败FaceID被锁住，接下来都是通过系统密码进行验证；        接下来是关键，你的SDK没有对用户点击取消按钮的事件进行处理，此时应该在点击取消时弹出系统密码进行验证。

**Comment by baiRookie** [comment]
所以，能够更新一下吗谢谢

**Comment by wuwuFQ** [comment]
> 面容识别失败三次后会弹出系统密码验证，不输入密码点取消还有两次面容识别，如果都失败FaceID被锁住，接下来都是通过系统密码进行验证； 接下来是关键，你的SDK没有对用户点击取消按钮的事件进行处理，此时应该在点击取消时弹出系统密码进行验证。


感谢反馈，SDK已优化， FQLockSDK (1.0.2)
用户验证多次失败后，面容ID被锁住，用户点击取消是响应取消的code，你再次点击验证会告诉你错误次数过多被锁住的code，这时需要你去提醒用户，你可以试试银行类App。（这个我在Demo里面已经标注了）
